name: Pest Tests

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: |
          php tests/patch.php
          ./vendor/bin/pest --group=SetupPagesInSeparatePHPUnitRun
          ./vendor/bin/pest
